# Generated by Django 3.0.8 on 2020-09-21 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='SSTV Image')),
                ('receive_date', models.DateTimeField(verbose_name='Date Received')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Comment Text')),
                ('comment_date', models.DateTimeField(verbose_name='Date Posted')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sstvgallery.Image')),
            ],
        ),
    ]
