# Generated by Django 3.0.8 on 2020-09-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sstvgallery', '0002_auto_20200921_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentor',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
